// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/bills/[fromDate].ts";
import * as $3 from "./routes/api/bills/download/[packageId].ts";
import * as $4 from "./routes/api/bills/summary/[packageId].ts";
import * as $5 from "./routes/committees/[offset]/[pagesize].tsx";
import * as $6 from "./routes/index.tsx";
import * as $7 from "./routes/partials/committees/[offset]/[pagesize].tsx";
import * as $8 from "./routes/partials/committees/subcommittees/[chamber]/[systemcode].tsx";
import * as $$0 from "./islands/BillSummaryAccordion.tsx";
import * as $$1 from "./islands/Bills.tsx";
import * as $$2 from "./islands/BillsNav.tsx";
import * as $$3 from "./islands/index.ts";

const manifest = {
	routes: {
		"./routes/_404.tsx": $0,
		"./routes/_app.tsx": $1,
		"./routes/api/bills/[fromDate].ts": $2,
		"./routes/api/bills/download/[packageId].ts": $3,
		"./routes/api/bills/summary/[packageId].ts": $4,
		"./routes/committees/[offset]/[pagesize].tsx": $5,
		"./routes/index.tsx": $6,
		"./routes/partials/committees/[offset]/[pagesize].tsx": $7,
		"./routes/partials/committees/subcommittees/[chamber]/[systemcode].tsx": $8,
	},
	islands: {
		"./islands/BillSummaryAccordion.tsx": $$0,
		"./islands/Bills.tsx": $$1,
		"./islands/BillsNav.tsx": $$2,
		"./islands/index.ts": $$3,
	},
	baseUrl: import.meta.url,
};

export default manifest;
